# Generated by Django 5.2.5 on 2025-08-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=50)),
                ("contactno", models.CharField(max_length=15)),
                ("subject", models.CharField(max_length=300)),
                ("message", models.TextField()),
                ("enqdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
