# Generated by Django 5.2.5 on 2025-08-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_logininfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("contactno", models.CharField(max_length=15)),
                ("password", models.CharField(max_length=100)),
                ("confirmpassword", models.CharField(max_length=100)),
                ("enqdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
